language: objective-c
os: osx
osx_image: xcode9.3
script:
  - xcodebuild test -scheme XCTAssertUnrecoverable-macOS -configuration Debug 
  - xcodebuild test -scheme XCTAssertUnrecoverable-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"
  - xcodebuild test -scheme XCTAssertUnrecoverable-tvOS -configuration Debug -sdk appletvsimulator -destination "name=Apple TV"
  - swift test

