env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
    - osx_image: xcode9.3
  before_install:
    - git submodule init --update --recursive
  script:
    - xcodebuild test -scheme XCTAssertUnrecoverable-macOS -configuration Debug 
    - xcodebuild test -scheme XCTAssertUnrecoverable-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"
    - xcodebuild test -scheme XCTAssertUnrecoverable-tvOS -configuration Debug -sdk appletvsimulator -destination "name=Apple TV"

